# Basic Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1[4]

4

In [ ]:
arr1[5:8]

array([5, 6, 7])

In [ ]:
arr2=arr1[5:8]
arr2

array([5, 6, 7])

In [ ]:
arr1[5:8]=12
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr1[9]=50
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8, 50])

In [ ]:
arr_slice=arr1[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1]=12345
arr1

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
          50])

In [ ]:
arr_slice[:]=64
arr_slice
arr1

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8, 50])

In [ ]:
arr1

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8, 50])

In [ ]:
aar2=arr1[5:8].copy()
aar2

array([64, 64, 64])

In [ ]:
aar2[:]=0
aar2
arr1

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8, 50])

In [4]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr3.shape

(3, 3)

In [ ]:
arr3[2]

array([7, 8, 9])

In [ ]:
arr3[0][2]

3

In [ ]:
arr3[0,2]

3

In [ ]:
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr4.shape

(2, 2, 3)

In [ ]:
arr4[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr4[0]=42
arr4

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr4[1,0]

array([7, 8, 9])

# indexing with slices

In [ ]:
arr1

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8, 50])

In [ ]:
arr1[1:6]

array([ 1,  2,  3,  4, 64])

In [5]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr5[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr5[1:2]

array([[4, 5, 6]])

In [ ]:
arr5[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr5[1,:2]

array([4, 5])

In [ ]:
arr5[:2,2]

array([3, 6])

In [ ]:
arr5[:,:1]

array([[1],
       [4],
       [7]])

# Boolean Indexing

In [14]:
name=np.array(['bob','joe','will','bob','will','joe','joe'])
name.shape


(7,)

In [12]:
data=np.random.randn(7,4)
data

array([[ 1.78940977,  0.73214771,  0.62698089,  1.41201412],
       [-0.23446161,  1.23152443, -0.22102647, -0.77679506],
       [-1.40645155,  1.51703657,  1.84446076,  0.28659818],
       [ 0.10052685, -1.31485254,  0.74447105,  0.40402202],
       [-2.34407195,  0.03041397,  0.58060746,  0.57107314],
       [ 0.03188256, -0.54782296, -0.53340032,  0.29814808],
       [-0.94867946, -0.22597306,  1.23662014, -1.08014986]])

In [15]:
name

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [16]:
name=='bob'

array([ True, False, False,  True, False, False, False])

In [17]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
data[0:3]

array([[ 0.77993733,  0.39186554, -0.50359625,  0.18215276],
       [ 0.2416554 ,  0.27698257,  0.09878798,  0.26731196],
       [ 0.29776064, -0.74203533,  1.08018392,  0.45849661]])

In [ ]:
data[0:4:3]

array([[ 0.77993733,  0.39186554, -0.50359625,  0.18215276],
       [-0.7882298 ,  0.45684627,  1.03530033,  0.674912  ]])

In [ ]:
data[name=='bob',2:]

array([[-0.50359625,  0.18215276],
       [ 1.03530033,  0.674912  ]])

# Fancy Indexing

In [ ]:
arr6=np.empty((8,4))
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(8):
    arr6[i]=i
arr6

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr7=arr6[[4,3,0,6]]
arr7

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr8=arr6[[-3,-5,-6]]

# Transposing Arrays and Swapping Axes

In [19]:
arr9=np.arange(15).reshape((3,5))
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
arr9.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr10=np.random.randn(6,3)
arr10

array([[ 0.35075153,  0.20895534, -0.84916112],
       [-0.83259729, -1.76035047, -0.55203499],
       [-0.81644809, -0.03210942, -1.00358299],
       [-0.91502384, -0.13872631, -0.72338636],
       [ 0.5847919 , -0.67295563, -0.38444336],
       [-0.81403113,  2.01672774, -0.53848782]])

In [ ]:
arr10.T

array([[ 0.35075153, -0.83259729, -0.81644809, -0.91502384,  0.5847919 ,
        -0.81403113],
       [ 0.20895534, -1.76035047, -0.03210942, -0.13872631, -0.67295563,
         2.01672774],
       [-0.84916112, -0.55203499, -1.00358299, -0.72338636, -0.38444336,
        -0.53848782]])

In [ ]:
np.dot(arr10.T,arr10)

array([[ 3.32472923, -0.34311017,  1.85659394],
       [-0.34311017,  7.68283219,  0.0996455 ],
       [ 1.85659394,  0.0996455 ,  2.99404973]])

In [ ]:
arr11=np.arange(16).reshape((2,2,4))
arr11

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr11.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr11.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
arr11.swapaxes(1,0)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# Universal Function: Fast Element-wise array

In [ ]:
arr12=np.arange(10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr12)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr12)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
arr13=np.random.randn(8)
arr14=np.random.randn(8)

In [ ]:
np.maximum(arr13,arr14)

array([ 1.8285095 , -0.91399866,  1.09150835, -0.52501256,  1.10180633,
        0.05031078,  1.26876528,  1.40266587])

In [ ]:
np.add(arr13,arr14)

array([ 2.60596165e+00, -1.99936979e+00,  6.07385634e-01, -1.10410419e+00,
        1.89531157e+00, -8.51959595e-04,  5.77743284e-01,  1.57071000e+00])

In [ ]:
#add,substract,multiply,fmax,mod,equal,......

# Array-Oriented Programming with Arrays

In [ ]:
#sqrt(x^2+y^2)= np.sqrt(x*x+y*y)

In [ ]:
x=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(x,x)

In [ ]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [ ]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

# Expressing Conditional Logic as Array Operation

In [ ]:
arr18=np.random.randn(4,4)

In [ ]:
arr18

array([[ 0.19077755, -0.74735802, -1.69964015,  0.45554285],
       [-0.53566158,  1.07329336, -1.69257817,  0.60966053],
       [-1.08970385, -1.0593399 , -1.02306684,  2.73050533],
       [-0.62027966,  0.75774922,  1.31769876, -0.17172349]])

In [ ]:
arr18>0

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [ ]:
np.where(arr18>0,2,12)

array([[ 2, 12, 12,  2],
       [12,  2, 12,  2],
       [12, 12, 12,  2],
       [12,  2,  2, 12]])

# Mathematical and Statistical Method

In [ ]:
arr19=np.random.randn(5,4)
arr19

array([[ 0.71942967, -0.06883966,  1.66997398,  2.32351916],
       [-0.415022  ,  1.67040724,  0.41455768,  0.11007692],
       [-0.56639812, -1.40563447,  1.16215666, -0.7603129 ],
       [ 0.49853367, -0.39037265, -0.11886142,  1.24185014],
       [ 0.05057716,  0.07959599,  1.47575914,  1.13909632]])

In [ ]:
arr19.mean()

0.4415046266586417

In [ ]:
np.mean(arr19)

0.4415046266586417

In [ ]:
arr19.sum()

8.830092533172834

In [ ]:
arr19.sum(axis=1)

array([ 4.64408316,  1.78001985, -1.57018883,  1.23114974,  2.74502861])

In [ ]:
#std,var,min,max,cumsum,cumpod

# Methods for Boolean Arrays

In [ ]:
import numpy as np

In [ ]:
arr20=np.random.randn(100)
arr20

array([-0.73544329, -0.87364506,  0.68941976, -0.11519489,  1.66021821,
       -0.37448328, -1.75282079,  0.45500955, -0.57299248,  1.1251641 ,
       -0.03547561, -0.35130902,  1.11812314,  0.43286929,  1.59575913,
       -1.75836202,  0.57633148,  1.29401825, -1.3972075 ,  0.37317533,
        1.3906241 , -0.01009467,  2.46925426, -0.653255  ,  1.87456622,
       -1.33467419, -1.24238282,  0.29366715, -0.86636235, -0.35803763,
        0.54435174, -0.09742072, -0.0502915 ,  0.43551546,  1.91466563,
       -0.89721068,  0.98864987, -0.85206161,  0.01172402, -0.37467269,
       -0.96091603,  1.71825331,  1.30234103,  0.81278589,  0.70261822,
       -1.23589118, -0.08217518,  0.71990269, -0.25107267, -0.83843535,
        2.6413808 ,  1.06927926,  0.70327332, -0.23171734, -0.39161738,
       -0.45625694,  0.44735967, -1.0136416 , -1.0732776 ,  0.75362548,
        0.44807315,  1.40489606,  1.43659619,  0.3476146 ,  0.71588668,
        0.58285431,  0.23872987,  0.44733557,  2.54333457, -0.84

In [ ]:
(arr20>0).sum()

57

In [ ]:
#any and all

In [ ]:
(arr20>0)

array([False, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True, False,  True, False, False,
        True, False, False,  True, False, False,  True,  True, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True,  True, False,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False, False, False, False,  True,
        True])

In [ ]:
arr21=(arr20>0)

In [ ]:
arr21.any()

True

In [ ]:
arr21.all()

False

# Sorting

In [ ]:
arr22=np.random.randn(6)
arr22

array([ 0.83982498,  0.82965094, -0.28498093,  0.05607504, -0.13135094,
       -0.35643791])

In [ ]:
arr22.sort()

In [ ]:
arr22

array([-0.35643791, -0.28498093, -0.13135094,  0.05607504,  0.82965094,
        0.83982498])

In [ ]:
arr23=np.random.randn(5,3)
arr23

array([[ 0.39251128,  0.04680192, -0.21387827],
       [-0.43117775, -0.27497342, -0.12494682],
       [-1.0609264 , -0.02210502,  1.62890011],
       [ 1.44127613,  0.45843806,  0.09832802],
       [-1.49799134,  1.16556871, -1.73454989]])

In [ ]:
arr23.shape

(5, 3)

In [ ]:
arr23.sort(1)

In [ ]:
arr23

array([[-0.21387827,  0.04680192,  0.39251128],
       [-0.43117775, -0.27497342, -0.12494682],
       [-1.0609264 , -0.02210502,  1.62890011],
       [ 0.09832802,  0.45843806,  1.44127613],
       [-1.73454989, -1.49799134,  1.16556871]])

In [ ]:
arr23.sort(0)

In [ ]:
arr23

array([[-1.73454989, -1.49799134, -0.12494682],
       [-1.0609264 , -0.27497342,  0.39251128],
       [-0.43117775, -0.02210502,  1.16556871],
       [-0.21387827,  0.04680192,  1.44127613],
       [ 0.09832802,  0.45843806,  1.62890011]])

# File Input and Output with arrays

In [ ]:
arr24=np.arange(10)
arr24

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('xyx',arr24)

In [ ]:
np.load('xyx.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])